const comforts = [
  'TV',
  'TV por cable',
  'Wifi',
  'Aire acondicionado',
  'Calefacción a gas',
  'Calefacción central',
  'Calefacción eléctrica',
  'Todo eléctrico',
  'Armarios empotrados',
  'Ascensor',
  'Lavadora',
  'Secadora',
  'Lavavajillas',
  'Portero',
  'Amueblado',
  'Utensilios básicos de cocina', 
  'Frigorífico',
  'Horno',
  'Agua Caliente',
  'Bañera',
  'Plato de ducha',
  'Vetanas de aluminio',
  'Ventanas de PVC',
  'Piscina',
  'Jacuzzi',
  'Terraza',
  'Balcón',
  'Terraza',
  'Vistas',
  'Jardín o patio interior',
  'Barbacoa',
  'Chimenea',
  'Gimnasio',
  'Accesible',
  'Entrada independiente',
  'Disponible para estancias cortas',
  'Aparcamiento gratuito en garaje',
  'Aparcamiento de pago garaje',
  'Aparcamiento de pago en la calle',
  'Aparcamiento gratuito en la calle',
  'Cargador para coches eléctricos',
  'Detector de monóxido de carbono',
  'Detector de humo'
];

module.exports = comforts;